site_name: 大富翁量化
site_url: http://www.jieyu.ai/
repo_url: https://github.com/zillionare/zillionare
repo_name: zillionare
site_description: 解剖量化框架软件,解读量化策略,分享量化课程与资源 for all quant traders
#strict: true

nav:
  - 首页: 'blog'
  - 量化课程:
    - ... | articles/coursea/cheese/**
  - 量化产品:
    - ... | articles/products/**
  - 策略研究:
    - ... | articles/investment/**
  - 学Python:
    - ... | articles/python/**
  - 文章分类: tags
  - 联系和关注: 
    - contact.md
theme:
  name: material
  language: zh
  logo: assets/img/logo.png
  custom_dir: docs/overrides
  palette:
    primary: light blue
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.instant
    - navigation.tabs.sticky
exclude_docs: |
  _drafts/
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 1
      permalink: true
  - meta
  - pymdownx.arithmatex:
      generic: true
plugins:
  - include-markdown
  - git-revision-date-localized
  - awesome-pages:
      collapse_single_pages: true
  - blog:
      post_excerpt_separator: <!--more-->
  - tags:
      tags_file: tags.md
  - rss:
      match_path: "(blog|articles)/.*"
      categories:
        - categories

        - tags
      date_from_meta:
        as_creation: date
      use_git: false
  - search:
      lang: zh
extra:
  social:
    - icon: fontawesome/brands/qq
      link: http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=zxYR3Hve6OMGLvEdgV4z_ONxcOF3hjMh&authKey=eoPjHqcwDIyiTQRNE6jGw1ReDajzXnGHtkAgwapdicr9n%2FPStD3FKit2miTi0zhC&noverify=0&group_code=578029127
      name: QQ群
    - icon: fontawesome/brands/zhihu
      link: https://www.zhihu.com/people/hbaaron
      name: 知乎
    - icon: fontawesome/brands/github
      link: https://github.com/zillionare
      name: Github
    - icon: material/email
      link: "mailto: aaron_yang@jieyu.ai"
  analytics:
    provider: google
    property: G-EHVH3XCS1V

extra_javascript:
  - overrides/javascripts/course.js
  # - assets/js/less.js
  - overrides/javascripts/katex.js
  - overrides/javascripts/katex.min.js
  - overrides/javascripts/auto-render.min.js

extra_css:
  - overrides/stylesheets/extra.css
  - overrides/stylesheets/katex.min.css
  # - assets/css/card.less
  # - assets/css/table.less
