site_name: 大富翁量化
site_url: http://www.jieyu.ai
repo_url: https://github.com/zillionare/zillionare
repo_name: zillionare
#strict: true

theme:
  name: material
  language: zh
  logo: assets/img/logo.png
  palette:
    primary: light blue
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.instant
    - navigation.tabs.sticky
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 1
      permalink: true
  - meta
plugins:
  - include-markdown
  - awesome-pages
  - blog
  - tags:
      tags_file: tags.md
  - rss:
      categories:
        - categories
        - tags
      date_from_meta:
        as_creation: date
  - search:
      lang: zh
extra:
  social:
    - icon: fontawesome/brands/zhihu
      link: https://www.zhihu.com/people/hbaaron
      name: 知乎
    - icon: fontawesome/brands/github
      link: https://github.com/zillionare
      name: Github
    - icon: material/email
      link: "mailto: aaron_yang@jieyu.ai"
  analytics:
    provider: google
    property: G-EHVH3XCS1V

extra_javascript:
  - assets/js/ad.js
  - assets/js/less.js

extra_css:
  - assets/css/extra.css
  # - assets/css/card.less
  # - assets/css/table.less
