[tool.poetry]
name = "zillionare"
version = "0.1.0"
description = ""
authors = ["aaron yang <aaron_yang@jieyu.ai>"]
readme = "README.md"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
secondary=false

[tool.poetry.dependencies]
python = "^3.8"
mkdocs  = { version = "^1.2.3"}
mkdocs-include-markdown-plugin  = { version = "^3.2.3"}
mkdocs-material  = { version = "^9.5.2"}
mkdocstrings  = { version = "^0.18.0"}
mkdocs-autorefs = {version = "^0.3.1"}
livereload = {version = "^2.6.3"}
mike = { version="^1.1.2", optional=true}
mkdocs-awesome-pages-plugin = "^2.8.0"
pre-commit = {version = "^2.17.0"}
fire = "^0.5.0"
markdown = "^3.4.4"
beautifulsoup4 = "^4.12.2"
pypandoc = "^1.11"
docxtpl = "^0.16.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
